### ISSUE TITLE
Criar logica firebase para signin

### ISSUE THREAD

**Issue by weslyh** [gladguys/easyIN#7]
- ao clicar em Entrar, deve ser feito request para firebase
- redirecionar para tela home apos login com sucesso. 
- exibir alert caso login falhe
- salvar dados do usuario  no local storage

**Comment by diCaminha** [comment]
Pra praticidade eu fiz o login e sign up numa mesma tela, num mesmo widget, ou seja, em um mesmo form. Assim, o local onde tu vai ter que trabalhar pra realizar a logica de signin e signup é aqui:

*na linha 90, faz a validação se o estado é de login ou signup, e ai tu faz o que for preciso dentro dos { }*

![image](https://user-images.githubusercontent.com/5836109/76687817-4e6fad00-6606-11ea-8b99-06496ab1df23.png)

**Comment by weslyh** [comment]
Feito. Talvez mereça uma refatoração.
